import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
import React, { useState } from "react";

export default function Home() {
    const [title, setTitle] = useState("Click");
    const [title2, setTitle2] = useState("Me");
    const [image, changeImage] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.maincontent}>
        <main className={styles.main}>
          <div>
            <div className={styles.header}>
            <h1 className={styles.joyce} onClick={() => setTitle("Joyce")}>{title}</h1>
            <Image
              className={styles.joyceimg}
              src={image ? "/joyceCat.png" : "/joyce.png"}
              width={540}
              height={540}
              onClick={() => changeImage(!image)}
            ></Image>
            <h1 className={styles.kim} onClick={() => setTitle2("Kim")}>{title2}</h1>
            </div>
            <div className={styles.uxui}>
            <h3 className={styles.h3}>UX/UI Designer</h3>
            <Image
              className={styles.wool}
              src="/wool.png"
              width={600}
              height={600}
            ></Image>
          </div>
          </div>
          <p className={styles.paragraph}>
            Hi, I am a multi-talented UX/UI Designer. I strive to create designs
            that tap into users' feelings and aspirations, helping them connect
            with the product on a deeper level.{" "}
          </p>
          <div className={styles.btn}>
            <Link href="" className={styles.linebtn}>Let's Talk</Link>
            <Link href="http://designer.joyceyunseo.ca/" className={styles.purplebtn}>View Portfolio</Link>
          </div>
          <h1 style={{textAlign: "center", fontSize: "40px", margin: "200px"}}>Services I Offer</h1>
          <div style={{textAlign: "center", fontSize: "40px"}}>
            <Image src="/mobile.png" width={400} height={320}></Image>
            <div style={{textAlign: "center", fontSize: "40px", margin: "100px"}}>Web UX/UI Design</div>
            <Image src="/web.png" width={200} height={350}></Image>
            <div style={{textAlign: "center", fontSize: "40px", margin: "100px"}}>Mobile App UX/UI Design</div>
            <Image src="/motion.png" width={300} height={180}></Image>
            <div style={{textAlign: "center", fontSize: "40px", margin: "100px"}}>Motion Graphic Design</div>
          </div>
        </main>
      </div>
      
    </>
  );
}

